name: mattermost main

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Install dependencies
      run: npm install
    - name: Build
      run: npx tsc
    - name: Send MatterMost Notification
      run: npx mattermost-ctrf results ctrf-report.json
      env:
        MATTERMOST_WEBHOOK_URL: ${{ vars.MATTERMOST_WEBHOOK_URL }}
        NODE_TLS_REJECT_UNAUTHORIZED: 0
    - name: Send Slack Notification
      run: npx mattermost-ctrf flaky ctrf-report.json
      env:
        MATTERMOST_WEBHOOK_URL: ${{ vars.MATTERMOST_WEBHOOK_URL }}
        NODE_TLS_REJECT_UNAUTHORIZED: 0
